server {
    listen 80;
    client_max_body_size 100m;

    location /auth/ {
        proxy_pass http://auth_service:8000;
    }

    location /upload/ {
        proxy_pass http://upload_service:8000;
    }

    location /feed/ {
        proxy_pass http://feed_service:8000;
    }

    location /videos/ {
        proxy_pass http://feed_service:8000;
    }

    location /users/ {
        proxy_pass http://feed_service:8000;
    }

    location /moderation/ {
        proxy_pass http://moderation_service:8000;
    }
}
